### ISSUE TITLE
A module is lost when the node is running in 16.15.1

### ISSUE THREAD

**Issue by sun511821811** [ErKeLost/unplugin-imagemin#46]
### Steps to reproduce

The window system is normally pulled to the macOS. After downloading the dependency operation, there is a lack of module. Cancel the image compression plug-in

### What is expected?

This can be fixed

### What is actually happening?

npm run dev

> doge-web@0.0.0 dev
> vite --open --host 0.0.0.0

failed to load config from /Users/minglongsun/Project/Doge-PC/vite.config.ts
error when starting dev server:
Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-darwin-x64.node'
Require stack:
- /Users/minglongsun/Project/Doge-PC/node_modules/unplugin-imagemin/node_modules/sharp/lib/sharp.js
- /Users/minglongsun/Project/Doge-PC/node_modules/unplugin-imagemin/node_modules/sharp/lib/constructor.js
- /Users/minglongsun/Project/Doge-PC/node_modules/unplugin-imagemin/node_modules/sharp/lib/index.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-x64 runtime: "npm install --platform=darwin --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Users/minglongsun/Project/Doge-PC/node_modules/unplugin-imagemin/node_modules/sharp/lib/sharp.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/minglongsun/Project/Doge-PC/node_modules/unplugin-imagemin/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

### System Info

```shell
macOS 13.3.1 (22E261)
node 16.15.1
vite 4.1.0
```

**Comment by ErKeLost** [comment]
Thank you for your use. I will check for problems with this version of node.

**Comment by sun511821811** [comment]
I tried to change the node version to 18 or higher, but the problem still seems to be not a single node version problem

**Comment by ErKeLost** [comment]
I think you should be using sharp mode for this mistake，Do you try to reinstall the dependency and run it again. It's supposed to be a mirror problem, and you can find it on sharp's website.

**Comment by ErKeLost** [comment]
Thank you for using it. I will help you if there are any problems.
